# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-08 17:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0008_auto_20160209_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField(verbose_name='Log Process date')),
                ('Events', models.IntegerField(verbose_name='Events stored in the system at that timestamp')),
                ('ID_Source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secapp.LogSources')),
            ],
        ),
    ]
