# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-16 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0003_auto_20160115_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ports',
            name='id_port',
        ),
        migrations.AddField(
            model_name='ports',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
