# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 20:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0006_visualizations_id_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualizations',
            name='Hour',
            field=models.IntegerField(verbose_name='Events process hour'),
        ),
    ]
