# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='Timestamp',
            field=models.DateTimeField(verbose_name='Log process date'),
        ),
        migrations.AlterField(
            model_name='events',
            name='Timestamp_Insertion',
            field=models.DateTimeField(verbose_name='Insertion bd date'),
        ),
        migrations.AlterField(
            model_name='packetadditionalinfo',
            name='ID_Tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_tag', to='secapp.Tags'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_Dest_MAC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_dest', to='secapp.Macs'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_Dest_Port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_dest', to='secapp.Ports'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_IP_Dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_dest', to='secapp.Ips'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_IP_Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_source', to='secapp.Ips'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_Source_MAC',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mac_source', to='secapp.Macs'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='ID_Source_Port',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='port_source', to='secapp.Ports'),
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='secapp.Events'),
        ),
    ]
