# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0005_visualizations'),
    ]

    operations = [
        migrations.AddField(
            model_name='visualizations',
            name='ID_Source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LogSource', to='secapp.LogSources'),
        ),
    ]
