# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 19:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.CharField(max_length=100)),
                ('Timestamp_Insertion', models.CharField(max_length=100)),
                ('Comment', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ip', models.CharField(max_length=60)),
                ('Hostname', models.CharField(max_length=60)),
                ('Tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogSources',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Type', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=255)),
                ('Active', models.SmallIntegerField()),
                ('Software_Class', models.CharField(max_length=50)),
                ('Path', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Macs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MAC', models.CharField(max_length=17)),
                ('TAG', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PacketAdditionalInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Value', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PacketEventsInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.CharField(max_length=20)),
                ('RAW_Info', models.TextField()),
                ('ID_Dest_MAC', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_dest', to='secapp.Macs')),
            ],
        ),
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id_port', models.IntegerField(primary_key=True, serialize=False)),
                ('Protocol', models.CharField(max_length=10)),
                ('Service', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=100)),
                ('Tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('Tag', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='ID_Dest_Port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_dest', to='secapp.Ports'),
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='ID_IP_Dest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_dest', to='secapp.Ips'),
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='ID_IP_Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ip_source', to='secapp.Ips'),
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='ID_Source_MAC',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mac_source', to='secapp.Macs'),
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='ID_Source_Port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_source', to='secapp.Ports'),
        ),
        migrations.AddField(
            model_name='packeteventsinformation',
            name='TAG',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='secapp.Tags'),
        ),
        migrations.AddField(
            model_name='packetadditionalinfo',
            name='ID_Tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secapp.Tags'),
        ),
        migrations.AddField(
            model_name='events',
            name='ID_Source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secapp.LogSources'),
        ),
    ]
