# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0003_auto_20151207_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ports',
            name='Protocol',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ports',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
