# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0005_auto_20151207_2122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ports',
        ),
    ]
