# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-07 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secapp', '0006_delete_ports'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Protocol', models.CharField(max_length=10)),
                ('Service', models.CharField(max_length=60)),
                ('Description', models.CharField(max_length=100)),
                ('Tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='packeteventsinformation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
